POST https://staging.hapity.com/api/fetch-google-access-token
Content-Type: application/json
Authorization: "Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwczpcL1wvc3RhZ2luZy5oYXBpdHkuY29tXC9hcGlcL2xvZ2luIiwiaWF0IjoxNjA1MDIyMjQxLCJuYmYiOjE2MDUwMjIyNDEsImp0aSI6IndYcGVGYXR1aWd2QW5QVUciLCJzdWIiOjIxNDQsInBydiI6Ijg3ZTBhZjFlZjlmZDE1ODEyZmRlYzk3MTUzYTE0ZTBiMDQ3NTQ2YWEifQ.3QSl4apfag8tGYZflFki29S5n9q1kjDTQhreTYH_VcE"

